"""
SQLAlchemy ORM models — V1 catalog schema.
All tables use UUID primary keys generated by the DB.
"""
from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


def _uuid() -> str:
    return str(uuid.uuid4())


class Base(DeclarativeBase):
    pass


# ---------------------------------------------------------------------------
# Assets
# ---------------------------------------------------------------------------


class Asset(Base):
    __tablename__ = "asset"

    id: Mapped[str] = mapped_column(UUID(as_uuid=False), primary_key=True, default=_uuid)
    canonical_path: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    filename: Mapped[str] = mapped_column(Text, nullable=False)
    extension: Mapped[str] = mapped_column(String(20), nullable=False)
    media_type: Mapped[str] = mapped_column(String(10), nullable=False)  # photo | video
    file_size_bytes: Mapped[int | None] = mapped_column(Integer)
    first_seen_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    last_seen_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())
    is_missing: Mapped[bool] = mapped_column(Boolean, default=False)
    source_root: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    hashes: Mapped[list[AssetHash]] = relationship(back_populates="asset", cascade="all, delete-orphan")
    media_info: Mapped[AssetMediaInfo | None] = relationship(back_populates="asset", uselist=False, cascade="all, delete-orphan")
    temporal: Mapped[AssetTemporal | None] = relationship(back_populates="asset", uselist=False, cascade="all, delete-orphan")
    location: Mapped[AssetLocation | None] = relationship(back_populates="asset", uselist=False, cascade="all, delete-orphan")
    thumbnails: Mapped[list[AssetThumbnail]] = relationship(back_populates="asset", cascade="all, delete-orphan")
    keyframes: Mapped[list[Keyframe]] = relationship(back_populates="asset", cascade="all, delete-orphan")
    extraction_runs: Mapped[list[ExtractionRun]] = relationship(back_populates="asset", cascade="all, delete-orphan")

    __table_args__ = (
        Index("ix_asset_media_type", "media_type"),
        Index("ix_asset_source_root", "source_root"),
        Index("ix_asset_first_seen", "first_seen_at"),
    )


class AssetHash(Base):
    __tablename__ = "asset_hash"

    id: Mapped[str] = mapped_column(UUID(as_uuid=False), primary_key=True, default=_uuid)
    asset_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("asset.id", ondelete="CASCADE"), nullable=False)
    hash_type: Mapped[str] = mapped_column(String(20), nullable=False)  # sha256 | phash | dhash
    hash_value: Mapped[str] = mapped_column(Text, nullable=False)
    computed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    asset: Mapped[Asset] = relationship(back_populates="hashes")

    __table_args__ = (
        UniqueConstraint("asset_id", "hash_type", name="uq_asset_hash_type"),
        Index("ix_asset_hash_value", "hash_type", "hash_value"),
    )


class AssetMediaInfo(Base):
    __tablename__ = "asset_media_info"

    id: Mapped[str] = mapped_column(UUID(as_uuid=False), primary_key=True, default=_uuid)
    asset_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("asset.id", ondelete="CASCADE"), nullable=False, unique=True)
    # Image / video dimensions
    width: Mapped[int | None] = mapped_column(Integer)
    height: Mapped[int | None] = mapped_column(Integer)
    # Video-specific
    duration_seconds: Mapped[float | None] = mapped_column(Float)
    video_codec: Mapped[str | None] = mapped_column(String(50))
    audio_codec: Mapped[str | None] = mapped_column(String(50))
    frame_rate: Mapped[float | None] = mapped_column(Float)
    # Camera
    make: Mapped[str | None] = mapped_column(Text)
    model: Mapped[str | None] = mapped_column(Text)
    # Raw payloads for provenance
    exiftool_raw: Mapped[dict | None] = mapped_column(JSONB)
    ffprobe_raw: Mapped[dict | None] = mapped_column(JSONB)
    extracted_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    asset: Mapped[Asset] = relationship(back_populates="media_info")


class AssetTemporal(Base):
    __tablename__ = "asset_temporal"

    id: Mapped[str] = mapped_column(UUID(as_uuid=False), primary_key=True, default=_uuid)
    asset_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("asset.id", ondelete="CASCADE"), nullable=False, unique=True)
    # Best timestamp (resolved from all sources)
    best_timestamp: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    best_timestamp_source: Mapped[str | None] = mapped_column(String(50))  # exif | gps | filesystem | video
    best_timestamp_confidence: Mapped[str | None] = mapped_column(String(20))  # high | medium | low
    # Raw sources (preserved)
    exif_datetime: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    gps_datetime: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    filesystem_mtime: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    video_creation_time: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    timezone_source: Mapped[str | None] = mapped_column(String(50))
    has_conflict: Mapped[bool] = mapped_column(Boolean, default=False)

    asset: Mapped[Asset] = relationship(back_populates="temporal")

    __table_args__ = (Index("ix_asset_temporal_best", "best_timestamp"),)


class AssetLocation(Base):
    __tablename__ = "asset_location"

    id: Mapped[str] = mapped_column(UUID(as_uuid=False), primary_key=True, default=_uuid)
    asset_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("asset.id", ondelete="CASCADE"), nullable=False, unique=True)
    latitude: Mapped[float | None] = mapped_column(Float)
    longitude: Mapped[float | None] = mapped_column(Float)
    altitude_m: Mapped[float | None] = mapped_column(Float)
    gps_source: Mapped[str | None] = mapped_column(String(30))  # exif | video
    location_raw: Mapped[dict | None] = mapped_column(JSONB)

    asset: Mapped[Asset] = relationship(back_populates="location")

    __table_args__ = (Index("ix_asset_location_coords", "latitude", "longitude"),)


# ---------------------------------------------------------------------------
# Derivatives
# ---------------------------------------------------------------------------


class AssetThumbnail(Base):
    __tablename__ = "asset_thumbnail"

    id: Mapped[str] = mapped_column(UUID(as_uuid=False), primary_key=True, default=_uuid)
    asset_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("asset.id", ondelete="CASCADE"), nullable=False)
    path: Mapped[str] = mapped_column(Text, nullable=False)
    width: Mapped[int] = mapped_column(Integer, nullable=False)
    height: Mapped[int] = mapped_column(Integer, nullable=False)
    generated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    asset: Mapped[Asset] = relationship(back_populates="thumbnails")

    __table_args__ = (UniqueConstraint("asset_id", "width", name="uq_thumbnail_asset_size"),)


class Keyframe(Base):
    __tablename__ = "keyframe"

    id: Mapped[str] = mapped_column(UUID(as_uuid=False), primary_key=True, default=_uuid)
    asset_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("asset.id", ondelete="CASCADE"), nullable=False)
    path: Mapped[str] = mapped_column(Text, nullable=False)
    offset_seconds: Mapped[float] = mapped_column(Float, nullable=False)
    sequence_index: Mapped[int] = mapped_column(Integer, nullable=False)
    generated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    asset: Mapped[Asset] = relationship(back_populates="keyframes")

    __table_args__ = (Index("ix_keyframe_asset", "asset_id", "sequence_index"),)


# ---------------------------------------------------------------------------
# Extraction
# ---------------------------------------------------------------------------


class ExtractionRun(Base):
    __tablename__ = "extraction_run"

    id: Mapped[str] = mapped_column(UUID(as_uuid=False), primary_key=True, default=_uuid)
    asset_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("asset.id", ondelete="CASCADE"), nullable=False)
    run_type: Mapped[str] = mapped_column(String(30), nullable=False)  # image | video | deterministic
    model_provider: Mapped[str | None] = mapped_column(String(50))
    model_name: Mapped[str | None] = mapped_column(String(100))
    schema_version: Mapped[str | None] = mapped_column(String(20))
    prompt_version: Mapped[str | None] = mapped_column(String(20))
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="pending")  # pending | running | done | failed
    raw_output: Mapped[dict | None] = mapped_column(JSONB)
    error_message: Mapped[str | None] = mapped_column(Text)
    tokens_in: Mapped[int | None] = mapped_column(Integer)
    tokens_out: Mapped[int | None] = mapped_column(Integer)
    cost_usd: Mapped[float | None] = mapped_column(Float)
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    asset: Mapped[Asset] = relationship(back_populates="extraction_runs")
    ocr_documents: Mapped[list[OcrDocument]] = relationship(back_populates="extraction_run", cascade="all, delete-orphan")
    object_detections: Mapped[list[ObjectDetection]] = relationship(back_populates="extraction_run", cascade="all, delete-orphan")
    scene_summaries: Mapped[list[SceneSummary]] = relationship(back_populates="extraction_run", cascade="all, delete-orphan")
    place_candidates: Mapped[list[PlaceCandidate]] = relationship(back_populates="extraction_run", cascade="all, delete-orphan")

    __table_args__ = (
        Index("ix_extraction_run_asset", "asset_id", "status"),
        Index("ix_extraction_run_model", "model_name", "schema_version"),
    )


class OcrDocument(Base):
    __tablename__ = "ocr_document"

    id: Mapped[str] = mapped_column(UUID(as_uuid=False), primary_key=True, default=_uuid)
    asset_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("asset.id", ondelete="CASCADE"), nullable=False)
    extraction_run_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("extraction_run.id", ondelete="CASCADE"), nullable=False)
    full_text: Mapped[str | None] = mapped_column(Text)
    language: Mapped[str | None] = mapped_column(String(10))
    confidence: Mapped[float | None] = mapped_column(Float)
    segments_raw: Mapped[list | None] = mapped_column(JSONB)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    asset: Mapped[Asset] = relationship()
    extraction_run: Mapped[ExtractionRun] = relationship(back_populates="ocr_documents")

    __table_args__ = (Index("ix_ocr_document_asset", "asset_id"),)


class ObjectDetection(Base):
    __tablename__ = "object_detection"

    id: Mapped[str] = mapped_column(UUID(as_uuid=False), primary_key=True, default=_uuid)
    asset_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("asset.id", ondelete="CASCADE"), nullable=False)
    extraction_run_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("extraction_run.id", ondelete="CASCADE"), nullable=False)
    label: Mapped[str] = mapped_column(Text, nullable=False)
    confidence: Mapped[float | None] = mapped_column(Float)
    attributes: Mapped[dict | None] = mapped_column(JSONB)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    asset: Mapped[Asset] = relationship()
    extraction_run: Mapped[ExtractionRun] = relationship(back_populates="object_detections")

    __table_args__ = (Index("ix_object_detection_label", "label"),)


class SceneSummary(Base):
    __tablename__ = "scene_summary"

    id: Mapped[str] = mapped_column(UUID(as_uuid=False), primary_key=True, default=_uuid)
    asset_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("asset.id", ondelete="CASCADE"), nullable=False)
    extraction_run_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("extraction_run.id", ondelete="CASCADE"), nullable=False)
    scene_type: Mapped[str | None] = mapped_column(Text)       # indoor | outdoor | urban | nature …
    setting: Mapped[str | None] = mapped_column(Text)          # restaurant | park | hospital …
    time_of_day: Mapped[str | None] = mapped_column(String(20))  # day | night | golden_hour …
    weather: Mapped[str | None] = mapped_column(Text)
    description: Mapped[str | None] = mapped_column(Text)
    confidence: Mapped[float | None] = mapped_column(Float)
    raw: Mapped[dict | None] = mapped_column(JSONB)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    asset: Mapped[Asset] = relationship()
    extraction_run: Mapped[ExtractionRun] = relationship(back_populates="scene_summaries")

    __table_args__ = (Index("ix_scene_summary_asset", "asset_id"),)


class PlaceCandidate(Base):
    __tablename__ = "place_candidate"

    id: Mapped[str] = mapped_column(UUID(as_uuid=False), primary_key=True, default=_uuid)
    asset_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("asset.id", ondelete="CASCADE"), nullable=False)
    extraction_run_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("extraction_run.id", ondelete="CASCADE"), nullable=False)
    name: Mapped[str | None] = mapped_column(Text)
    country: Mapped[str | None] = mapped_column(String(100))
    region: Mapped[str | None] = mapped_column(Text)
    place_type: Mapped[str | None] = mapped_column(Text)  # city | landmark | neighborhood …
    confidence: Mapped[float | None] = mapped_column(Float)
    source: Mapped[str | None] = mapped_column(String(30))  # gps | ai | exif
    raw: Mapped[dict | None] = mapped_column(JSONB)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    asset: Mapped[Asset] = relationship()
    extraction_run: Mapped[ExtractionRun] = relationship(back_populates="place_candidates")

    __table_args__ = (Index("ix_place_candidate_asset", "asset_id"),)


# ---------------------------------------------------------------------------
# Assertions
# ---------------------------------------------------------------------------


class Assertion(Base):
    __tablename__ = "assertion"

    id: Mapped[str] = mapped_column(UUID(as_uuid=False), primary_key=True, default=_uuid)
    asset_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("asset.id", ondelete="CASCADE"), nullable=False)
    predicate: Mapped[str] = mapped_column(Text, nullable=False)  # e.g. "scene.setting"
    value: Mapped[str] = mapped_column(Text, nullable=False)
    confidence: Mapped[float | None] = mapped_column(Float)
    source: Mapped[str | None] = mapped_column(String(30))  # model | user | deterministic
    extraction_run_id: Mapped[str | None] = mapped_column(UUID(as_uuid=False), ForeignKey("extraction_run.id"))
    superseded_by: Mapped[str | None] = mapped_column(UUID(as_uuid=False), ForeignKey("assertion.id"))
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    user_verified: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    __table_args__ = (Index("ix_assertion_asset_predicate", "asset_id", "predicate", "is_active"),)


# ---------------------------------------------------------------------------
# Jobs
# ---------------------------------------------------------------------------


class JobRun(Base):
    __tablename__ = "job_run"

    id: Mapped[str] = mapped_column(UUID(as_uuid=False), primary_key=True, default=_uuid)
    job_type: Mapped[str] = mapped_column(String(30), nullable=False)  # scan | enrich | extract | reprocess
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="queued")
    source_root: Mapped[str | None] = mapped_column(Text)
    asset_ids: Mapped[list | None] = mapped_column(JSONB)
    progress_current: Mapped[int] = mapped_column(Integer, default=0)
    progress_total: Mapped[int] = mapped_column(Integer, default=0)
    message: Mapped[str | None] = mapped_column(Text)
    error: Mapped[str | None] = mapped_column(Text)
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    __table_args__ = (
        Index("ix_job_run_status", "status", "started_at"),
    )


# ---------------------------------------------------------------------------
# Review
# ---------------------------------------------------------------------------


class ReviewAction(Base):
    __tablename__ = "review_action"

    id: Mapped[str] = mapped_column(UUID(as_uuid=False), primary_key=True, default=_uuid)
    asset_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("asset.id", ondelete="CASCADE"), nullable=False)
    queue: Mapped[str] = mapped_column(String(30), nullable=False)  # duplicate | ocr | temporal | place
    decision: Mapped[str] = mapped_column(String(20), nullable=False)  # reviewed | deferred | flagged
    notes: Mapped[str | None] = mapped_column(Text)
    reviewed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    __table_args__ = (Index("ix_review_action_asset", "asset_id", "queue"),)


# ---------------------------------------------------------------------------
# Collections
# ---------------------------------------------------------------------------


class Collection(Base):
    __tablename__ = "collection"

    id: Mapped[str] = mapped_column(UUID(as_uuid=False), primary_key=True, default=_uuid)
    name: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    description: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    members: Mapped[list[CollectionAsset]] = relationship(back_populates="collection", cascade="all, delete-orphan")


class CollectionAsset(Base):
    __tablename__ = "collection_asset"

    collection_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("collection.id", ondelete="CASCADE"), primary_key=True)
    asset_id: Mapped[str] = mapped_column(UUID(as_uuid=False), ForeignKey("asset.id", ondelete="CASCADE"), primary_key=True)
    added_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    collection: Mapped[Collection] = relationship(back_populates="members")
