"""v1_initial_schema

Revision ID: 4f1e280d00cf
Revises: 
Create Date: 2026-03-14 00:39:36.567930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f1e280d00cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('canonical_path', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=False),
    sa.Column('media_type', sa.String(length=10), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_missing', sa.Boolean(), nullable=False),
    sa.Column('source_root', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_path')
    )
    op.create_index('ix_asset_first_seen', 'asset', ['first_seen_at'], unique=False)
    op.create_index('ix_asset_media_type', 'asset', ['media_type'], unique=False)
    op.create_index('ix_asset_source_root', 'asset', ['source_root'], unique=False)
    op.create_table('collection',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('job_run',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_root', sa.Text(), nullable=True),
    sa.Column('asset_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_run_status', 'job_run', ['status', 'started_at'], unique=False)
    op.create_table('asset_hash',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('hash_type', sa.String(length=20), nullable=False),
    sa.Column('hash_value', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'hash_type', name='uq_asset_hash_type')
    )
    op.create_index('ix_asset_hash_value', 'asset_hash', ['hash_type', 'hash_value'], unique=False)
    op.create_table('asset_location',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude_m', sa.Float(), nullable=True),
    sa.Column('gps_source', sa.String(length=30), nullable=True),
    sa.Column('location_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_index('ix_asset_location_coords', 'asset_location', ['latitude', 'longitude'], unique=False)
    op.create_table('asset_media_info',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('video_codec', sa.String(length=50), nullable=True),
    sa.Column('audio_codec', sa.String(length=50), nullable=True),
    sa.Column('frame_rate', sa.Float(), nullable=True),
    sa.Column('make', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('exiftool_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ffprobe_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_table('asset_temporal',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('best_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('best_timestamp_source', sa.String(length=50), nullable=True),
    sa.Column('best_timestamp_confidence', sa.String(length=20), nullable=True),
    sa.Column('exif_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gps_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filesystem_mtime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('video_creation_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone_source', sa.String(length=50), nullable=True),
    sa.Column('has_conflict', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_index('ix_asset_temporal_best', 'asset_temporal', ['best_timestamp'], unique=False)
    op.create_table('asset_thumbnail',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'width', name='uq_thumbnail_asset_size')
    )
    op.create_table('collection_asset',
    sa.Column('collection_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'asset_id')
    )
    op.create_table('extraction_run',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('run_type', sa.String(length=30), nullable=False),
    sa.Column('model_provider', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('schema_version', sa.String(length=20), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_extraction_run_asset', 'extraction_run', ['asset_id', 'status'], unique=False)
    op.create_index('ix_extraction_run_model', 'extraction_run', ['model_name', 'schema_version'], unique=False)
    op.create_table('keyframe',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('offset_seconds', sa.Float(), nullable=False),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_keyframe_asset', 'keyframe', ['asset_id', 'sequence_index'], unique=False)
    op.create_table('review_action',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('queue', sa.String(length=30), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_action_asset', 'review_action', ['asset_id', 'queue'], unique=False)
    op.create_table('assertion',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('predicate', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('extraction_run_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('superseded_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_run.id'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['assertion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assertion_asset_predicate', 'assertion', ['asset_id', 'predicate', 'is_active'], unique=False)
    op.create_table('object_detection',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('extraction_run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_object_detection_label', 'object_detection', ['label'], unique=False)
    op.create_table('ocr_document',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('extraction_run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('segments_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ocr_document_asset', 'ocr_document', ['asset_id'], unique=False)
    op.create_table('place_candidate',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('extraction_run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('place_type', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_place_candidate_asset', 'place_candidate', ['asset_id'], unique=False)
    op.create_table('scene_summary',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('asset_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('extraction_run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scene_type', sa.Text(), nullable=True),
    sa.Column('setting', sa.Text(), nullable=True),
    sa.Column('time_of_day', sa.String(length=20), nullable=True),
    sa.Column('weather', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scene_summary_asset', 'scene_summary', ['asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scene_summary_asset', table_name='scene_summary')
    op.drop_table('scene_summary')
    op.drop_index('ix_place_candidate_asset', table_name='place_candidate')
    op.drop_table('place_candidate')
    op.drop_index('ix_ocr_document_asset', table_name='ocr_document')
    op.drop_table('ocr_document')
    op.drop_index('ix_object_detection_label', table_name='object_detection')
    op.drop_table('object_detection')
    op.drop_index('ix_assertion_asset_predicate', table_name='assertion')
    op.drop_table('assertion')
    op.drop_index('ix_review_action_asset', table_name='review_action')
    op.drop_table('review_action')
    op.drop_index('ix_keyframe_asset', table_name='keyframe')
    op.drop_table('keyframe')
    op.drop_index('ix_extraction_run_model', table_name='extraction_run')
    op.drop_index('ix_extraction_run_asset', table_name='extraction_run')
    op.drop_table('extraction_run')
    op.drop_table('collection_asset')
    op.drop_table('asset_thumbnail')
    op.drop_index('ix_asset_temporal_best', table_name='asset_temporal')
    op.drop_table('asset_temporal')
    op.drop_table('asset_media_info')
    op.drop_index('ix_asset_location_coords', table_name='asset_location')
    op.drop_table('asset_location')
    op.drop_index('ix_asset_hash_value', table_name='asset_hash')
    op.drop_table('asset_hash')
    op.drop_index('ix_job_run_status', table_name='job_run')
    op.drop_table('job_run')
    op.drop_table('collection')
    op.drop_index('ix_asset_source_root', table_name='asset')
    op.drop_index('ix_asset_media_type', table_name='asset')
    op.drop_index('ix_asset_first_seen', table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
